#
# Copyright (c) 2002 by Naohide Sano, All rights reserved.
#
# Properties File for JBeansTabbedPane.
#
# 0.00 020512 nsano initial version
#

#
# the font editor class name
# must be implemented vavi.swing.fontchooser.FontEditor
#
#editorClass=vavi.swing.fontchooser.DefaultFontEditor
editorClass=vavi.swing.fontchooser.SmallFontEditor

#
# the default font, the format is java.awt.Font#decode(String)
#
#   fontname-style-pointsize
#
# @param style PLAIN, BOLD, ITALIC, BOLDITALIC
#
font=Dialog-BOLD-12
#font=Dialog-PLAIN-12

##
