#
# Copyright (c) 2002 by Naohide Sano, All rights reserved.
#
# Written by Naohide Sano
#
# Properties File for the LayoutManagerChooser.
#
# 0.00 020517 nsano initial version
#
# the sample list is moved to layoutManager.xml
#

#
# LayoutManagerChooser
#
editor.1=java.awt.GridLayout
editor.2=java.awt.FlowLayout
editor.3=java.awt.CardLayout
editor.4=java.awt.BorderLayout
editor.5=java.awt.GridBagLayout
editor.6=javax.swing.BoxLayout

##
