#
# Copyright (c) 2002 by Naohide Sano, All rights reserved.
#
# Written by Naohide Sano
#
# Properties File for the BorderChooser.
#
# 0.00 020517 nsano initial version
#
# the sample list is moved to border.xml
#

#
# BorderChooser
#
editor.1=javax.swing.border.SoftBevelBorder
editor.2=javax.swing.border.BevelBorder
editor.3=javax.swing.border.EtchedBorder
editor.4=javax.swing.border.LineBorder
editor.5=javax.swing.border.MatteBorder
editor.6=javax.swing.border.TitledBorder
editor.7=javax.swing.border.CompoundBorder
editor.8=javax.swing.border.EmptyBorder

##
